export const FETCH_USER_DETAILS="FETCH_USER_DETAILS";
export const SUCESS_FETCH_USER_DETAILS="SUCESS_FETCH_USER_DETAILS";
export const FAIL_FETCH_USER_DETAILS="FAIL_FETCH_USER_DETAILS";
export const USER_MOST_RESCENT_WORK="USER_MOST_RESCENT_WORK";
export const USER_MOST_RESCENT_TIME_LOG="USER_MOST_RESCENT_TIME_LOG";