export const GET_ALL_HORA_SERVICE_SUCCESS = "GET_ALL_HORA_SERVICE_SUCCESS";
export const GET_ALL_HORA_SERVICE_FAILURE = "GET_ALL_HORA_SERVICE_FAILURE";
export const GET_ALL_HORA_SERVICE_LOADING = "GET_ALL_HORA_SERVICE_LOADING";