export const FETCH_IN_APP_NOTIFICATIONS_REQUEST = "FETCH_IN_APP_NOTIFICATIONS_REQUEST";
export const FETCH_IN_APP_NOTIFICATIONS_SUCCESS = "FETCH_IN_APP_NOTIFICATIONS_SUCCESS";
export const FETCH_IN_APP_NOTIFICATIONS_FAILURE = "FETCH_IN_APP_NOTIFICATIONS_FAILURE";

export const MARK_AS_READ_NOTIFICATION_REQUEST = "MARK_AS_READ_NOTIFICATION_REQUEST";
export const MARK_AS_READ_NOTIFICATION_SUCCESS = "MARK_AS_READ_NOTIFICATION_SUCCESS";
export const MARK_AS_READ_NOTIFICATION_FAILURE = "MARK_AS_READ_NOTIFICATION_FAILURE";

export const GET_NOTIFICATION_ANALYTICS_REQUEST = "GET_NOTIFICATION_ANALYTICS_REQUEST";
export const GET_NOTIFICATION_ANALYTICS_SUCCESS = "GET_NOTIFICATION_ANALYTICS_SUCCESS";
export const GET_NOTIFICATION_ANALYTICS_FAILURE = "GET_NOTIFICATION_ANALYTICS_FAILURE";
export const FETCH_NEW_NOTIFICATION = "FETCH_NEW_NOTIFICATION";
export const HANDLE_NOTIFACTION_SIDE_PANEL = "HANDLE_NOTIFACTION_SIDE_PANEL";

