// export const GET_OTP = "GET_OTP";
// export const VERIFY_OTP = "VERIFY_OTP";
// export const REGISTER_USER = "REGISTER_USER";
// export const LOGIN_USER = "LOGIN_USER";
// export const LOGOUT_USER = "LOGOUT_USER";
// export const REQUIRES_REGISTRATION = "REQUIRES_REGISTRATION";
// export const VERIFIED_USER_AND_LOGIN = "VERIFIED_USER_AND_LOGIN";
// Auth Constants
export const GET_OTP = 'GET_OTP';
export const GET_OTP_SUCCESS = 'GET_OTP_SUCCESS';
export const GET_OTP_ERROR = 'GET_OTP_ERROR';

export const VERIFY_OTP = 'VERIFY_OTP';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_ERROR = 'VERIFY_OTP_ERROR';

export const REQUIRES_REGISTRATION = 'REQUIRES_REGISTRATION';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const VERIFIED_USER_AND_LOGIN = 'VERIFIED_USER_AND_LOGIN';

export const VERIFY_ACCOUNT = 'VERIFY_ACCOUNT';
export const VERIFY_ACCOUNT_SUCCESS = 'VERIFY_ACCOUNT_SUCCESS';
export const VERIFY_ACCOUNT_ERROR = 'VERIFY_ACCOUNT_ERROR';

export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const ACCOUNT_VERIFIACTION_SUCESS = 'ACCOUNT_VERIFIACTION_SUCESS';
export const ACCOUNT_VERIFIACTION_FAIL = 'ACCOUNT_VERIFIACTION_FAIL';

export const TOKEN_VALIDATION_SUCCESS = 'TOKEN_VALIDATION_SUCCESS';
export const TOKEN_VALIDATION_FAILED = 'TOKEN_VALIDATION_FAILED';