export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const GET_PROJECT_BY_ID = "GET_PROJECT_BY_ID";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const GET_PROJECT_TASKS = "GET_PROJECT_TASKS";
export const FETCH_PROJECT_WITH_HIGHER_ACCESS = "FETCH_PROJECT_WITH_HIGHER_ACCESS";
export const PROJECT_CONFIG_FETCH_SUCESS = "PROJECT_CONFIG_FETCH_SUCESS";
export const PROJECT_CONFIG_FETCH_LOADING = "PROJECT_CONFIG_FETCH_LOADING";

export const PROJECT_MEMBERS_LOADING = "PROJECT_MEMBERS_LOADING";
export const PROJECT_MEMBERS_SUCCESS = "PROJECT_MEMBERS_SUCCESS";
export const PROJECT_MEMBERS_ERROR = "PROJECT_MEMBERS_ERROR";