export const GET_ALL_TICKETS="GET_ALL_TICKETS";
export const GET_TICKET_BY_ID="GET_TICKET_BY_ID";
export const CREATE_TICKET="CREATE_TICKET";
export const UPDATE_TICKET="UPDATE_TICKET";     
export const DELETE_TICKET="DELETE_TICKET";
export const GET_TICKET_COMMENTS="GET_TICKET_COMMENTS";
export const CREATE_TICKET_COMMENT="CREATE_TICKET_COMMENT";
export const UPDATE_TICKET_COMMENT="UPDATE_TICKET_COMMENT";
export const OPEN_CREATE_TICKET_POPUP="OPEN_CREATE_TICKET_POPUP";
export const SET_FILTERED_TICKETS="SET_FILTERED_TICKETS";

// New constants for real-time updates
export const UPDATE_TICKET_STATUS="UPDATE_TICKET_STATUS";
export const ADD_TICKET_TIME_LOG="ADD_TICKET_TIME_LOG";
export const ASSIGN_TICKET="ASSIGN_TICKET";
export const GET_TICKET_UPDATED_DETAILS="GET_TICKET_UPDATED_DETAILS";
export const SET_SELECTED_TICKET="SET_SELECTED_TICKET";
export const GET_ACTIVITY_LOGS_REQUEST="GET_ACTIVITY_LOGS_REQUEST";
export const GET_ACTIVITY_LOGS_SUCCESS="GET_ACTIVITY_LOGS_SUCCESS";